FROM eclipse-temurin:11-jdk-jammy@sha256:f2e5cb53ab0fbcf0b4e0cbe963f684f524ea493835e6c36617536caac53ad4b6
# Android Dependencies
# --------------------
# Adapt the parameters below to change the dependencies.
#

ARG ANDROID_API_LEVEL=28
ARG ANDROID_BUILD_TOOLS_LEVEL=30.0.3
ARG ANDROID_NDK_VERSION=21.1.6352462
ARG ANDROID_CLI_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip"
ARG SDKMANAGER_PACKAGES="build-tools;${ANDROID_BUILD_TOOLS_LEVEL} platforms;android-$ANDROID_API_LEVEL cmake;3.6.4111459 system-images;android-28;default;x86_64 emulator"

# Arguments, Environment
# ----------------------
#
# Default values for the arguments to be passed from the Jenkinsfile.
# Those contain the uid and gid of the Jenkins user, and are used to
# create this user inside of the container, needed for eg ssh-agent to work

ARG USER_ID=1000
ARG USER_HOME=/home/user
ARG GROUP_ID=1000
ARG KVM_GROUP_ID=999

# Environment variables that are needed by the build job.
ENV ANDROID_SDK_ROOT=$USER_HOME/android/sdk
ENV ANDROID_AVD_HOME=$USER_HOME/avds

# SDK paths
ARG _SDKMANAGER=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager
ARG _CMD_LINE=$ANDROID_SDK_ROOT/cmdline-tools
ARG _SDK_TMP_ZIP=/tmp/android_sdk.zip

# Deprecated: Still used by gradle, once gradle respects ANDROID_SDK_ROOT, this can be removed
ENV ANDROID_HOME=$ANDROID_SDK_ROOT
ENV PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator

# Performance related settings for the JVM
# - Respect the cgroup settings for memory.
#
# Note: Usage of _JAVA_OPTIONS is in general discouraged.
#       This is an internal flag that will be preferred over
#       JAVA_TOOL_OPTIONS and the command line parameters.
#       We still use it here to ensure that these settings
#       are respected, no matter what is configured elsewhere.
ENV _JAVA_OPTIONS="-XX:+UnlockExperimentalVMOptions"

# System Packages
# ---------------
#
# x11-commons/x11-utils/libpulse0 needed to start emulator
RUN apt-get update && apt-get install -y --no-install-recommends \
        git=1:2.34.1-1ubuntu1.15 \
        libasound2 \
        libnss3-dev \
        libpulse0 \
        libxcursor-dev \
        python2=2.7.* \
        unzip \
        x11-common \
        x11-utils \
        #ruby-full \
        rubygems \
        ruby-dev \
        g++ \
        make \
        less \
    && rm -rf /var/lib/apt/lists/* \
    && gem install rake \
    && gem install fastlane -NV

# User Management
# ---------------
#
# add the 'Jenkins' user
# Add group of the user used by Jenkins during building.
RUN if [ ! $(getent group $GROUP_ID) ]; then groupadd -g $GROUP_ID user; fi &&\
    groupadd -g $KVM_GROUP_ID kvm &&\
    mkdir -p catroid/build/reports/jacoco/jacocoTestCatroidDebugUnitTestReport/html  &&\
    mkdir -p catroid/build/reports/coverage/catroid/debug/

# Add the user used by Jenkins during building.
RUN useradd -m -u $USER_ID -g $GROUP_ID -G $KVM_GROUP_ID -d $USER_HOME -s /usr/sbin/nologin user
# Run all other commands as user
USER user
RUN mkdir -p $ANDROID_AVD_HOME

# Android SDK
# ------------------
#

ADD --chown=user:user $ANDROID_CLI_TOOLS_URL $_SDK_TMP_ZIP
RUN mkdir -p $ANDROID_SDK_ROOT \
    && unzip -d $ANDROID_SDK_ROOT $_SDK_TMP_ZIP \
    && rm $_SDK_TMP_ZIP \
    && mkdir -p $_CMD_LINE/latest \
    && mv $_CMD_LINE/bin $_CMD_LINE/lib $_CMD_LINE/source.properties $_CMD_LINE/latest/

# Android NDK (unused)
# ----------------
#
# RUN if [ ! -z "$ANDROID_NDK_URL" ]; then \
#         curl $ANDROID_NDK_URL --output /tmp/android_ndk.zip \
#         && mkdir -p $ANDROID_SDK_ROOT /tmp/ndk \
#         && unzip -d /tmp/ndk /tmp/android_ndk.zip \
#         && mv /tmp/ndk/* $ANDROID_SDK_ROOT/ndk-bundle \
#         && rm /tmp/android_ndk.zip; \
#     fi
#

# Installing SDK Packages
# -----------------------
#
RUN if [ ! -z "$SDKMANAGER_PACKAGES" ]; then yes | $_SDKMANAGER $SDKMANAGER_PACKAGES; fi

# Accept SDK licenses
RUN yes | $_SDKMANAGER --licenses

CMD ["bash"]
