import io.gitlab.arturbosch.detekt.Detekt

/**
 *  Paintroid: An image manipulation application for Android.
 *  Copyright (C) 2010-2022 The Catrobat Team
 *  (<http://developer.catrobat.org/credits>)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

plugins {
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
}

ext {
    appId = "org.catrobat.paintroid"
    appName = "@string/pocketpaint_app_name"
}

// Allow multiple side-by-side installs when run with -Pindependent
if (project.hasProperty("independent")) {
    def today = new Date()
    appId += ".independent_${today.format('yyyyMMdd_HHmm')}"
    appName = property("independent") ?: "Paint ${today.format('MMdd HH:mm')}"
}

// Provide a dummy keystore if none is passed
if (!project.hasProperty("signingKeystore")) {
    ext.signingKeystore = "dummyKeystore"
}

android {
    namespace "org.catrobat.paintroid.app"
    compileSdk = rootProject.ext.androidCompileSdkVersion

    defaultConfig {
        applicationId appId
        minSdk  = rootProject.ext.androidMinSdkVersion
        targetSdk = rootProject.ext.androidTargetSdkVersion
        versionCode = rootProject.ext.androidVersionCode
        versionName = rootProject.ext.androidVersionName
        manifestPlaceholders += [appName: appName]
        setProperty("archivesBaseName", "paintroid")
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }

    signingConfigs {
        signedRelease {
            storeFile file(project.property("signingKeystore"))
            storePassword ""
            keyAlias ""
            keyPassword ""
        }
    }

    if (project.hasProperty("signingKeystore") &&
            project.hasProperty("signingKeystorePassword") &&
            project.hasProperty("signingKeyAlias") &&
            project.hasProperty("signingKeyPassword")) {

        signingConfigs.signedRelease.storePassword = project.property("signingKeystorePassword")
        signingConfigs.signedRelease.keyAlias      = project.property("signingKeyAlias")
        signingConfigs.signedRelease.keyPassword   = project.property("signingKeyPassword")
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
        create("signedRelease") {
            initWith(buildTypes.release)
            signingConfig = signingConfigs.signedRelease
        }
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
    packaging {
        jniLibs {
            useLegacyPackaging false
        }
    }
}

tasks.withType(io.gitlab.arturbosch.detekt.Detekt).configureEach {
    jvmTarget = "17"
    exclude("**/resources/**")
    exclude("**/build/**")
}

dependencies {
    implementation project(":Paintroid")
    implementation "com.android.support:support-core-utils:28.0.0"
}

